// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-7G-RSB92tbckNVg8HK5QC-wQSKYGKXI',
    appId: '1:345308746568:web:e158b9d4b46194e2fb197d',
    messagingSenderId: '345308746568',
    projectId: 'starubigaz',
    authDomain: 'starubigaz.firebaseapp.com',
    storageBucket: 'starubigaz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzpKHHRC7UUmjfZ5y2cLYxFaakXoj0Qsg',
    appId: '1:345308746568:android:29abc7004212470bfb197d',
    messagingSenderId: '345308746568',
    projectId: 'starubigaz',
    storageBucket: 'starubigaz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ZEIDurEdTRxN5pAHhO5s8JD_qyUVPrM',
    appId: '1:345308746568:ios:fc383c07231bacc0fb197d',
    messagingSenderId: '345308746568',
    projectId: 'starubigaz',
    storageBucket: 'starubigaz.appspot.com',
    iosBundleId: 'com.example.loginFirebaseBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ZEIDurEdTRxN5pAHhO5s8JD_qyUVPrM',
    appId: '1:345308746568:ios:fc383c07231bacc0fb197d',
    messagingSenderId: '345308746568',
    projectId: 'starubigaz',
    storageBucket: 'starubigaz.appspot.com',
    iosBundleId: 'com.example.loginFirebaseBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-7G-RSB92tbckNVg8HK5QC-wQSKYGKXI',
    appId: '1:345308746568:web:6e7b9640a7fe563cfb197d',
    messagingSenderId: '345308746568',
    projectId: 'starubigaz',
    authDomain: 'starubigaz.firebaseapp.com',
    storageBucket: 'starubigaz.appspot.com',
  );
}
