name: user_repository
description: The repo that handles the users
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
